### ISSUE TITLE
Exception - Place the main idea before exceptions and conditions

### ISSUE THREAD

**Issue by yichiang** [yichiang/plain-language-checker#11]
https://www.plainlanguage.gov/guidelines/organize/place-the-main-idea-before-exceptions-and-conditions/

**Comment by adelapen** [comment]
Taken from https://www.plainlanguage.gov/guidelines/organize/place-the-main-idea-before-exceptions-and-conditions/. Find the substring “except”, also look for “unless”. Could also look for “if” and include the feedback as a kudo.
