### ISSUE TITLE
Avoid jargon

### ISSUE THREAD

**Issue by yichiang** [yichiang/plain-language-checker#14]
https://www.plainlanguage.gov/guidelines/words/avoid-jargon/

**Comment by adelapen** [comment]
We have a list of words here that we can just check against.

**Comment by yichiang** [comment]
Hi @adelapen, do you think you could share the list? Thank you.

**Comment by adelapen** [comment]
> Hi @adelapen, do you think you could share the list? Thank you.

For sure, they live here https://github.com/yichiang/plain-language-checker/blob/main/src/Jargon.txt
