### ISSUE TITLE
Don’t use slashes:

### ISSUE THREAD

**Issue by yichiang** [yichiang/plain-language-checker#9]

**Comment by adelapen** [comment]
@yichiang one thing to watch out for here is that there can be 2 cases:

1) a and/or b -> a or b or both

If the slash is part of the string "and/or" or "or/and" we want to show this suggestion

2) / -> and, or

If the slash is for some other words, we want to show this suggestion

**Comment by yichiang** [comment]
Sounds good. Thank you for the example @adelapen. Since it is nice to have, I will work on the other feature #7 first next weekend.
